version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: krahal/node-docker-tutorial:latest
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:3000"
    networks:
      - webnet
networks:
  webnet: